title: Automatic Indoor Tracking in Workplaces
email: ben@notionparallax.co.uk
description: > # this means to ignore newlines until "baseurl:"
    We are experimenting with indoor tracking technologies. This is our logbook
    to write down what we are doing and whatever!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://where-in.space" # the base hostname & protocol for your site
twitter_username: whereinspace #the twitter account for this project

#Timezone settings
timezone: Australia/Sydney

#google analytics
GAcode: UA-76337945-1

# Build settings
permalink: "/:year/:title"
markdown: kramdown
kramdown:
  parse_block_html: true

authors:
  alex:
    display_name: Alexander Lee
    first_name: Alexander
    last_name: Lee
    twitter_username: alexlee #personal twitter account
    github_username:  tuksun
    facebookURL:  XenriaLee          # ignore the https://www.facebook.com/ part
    instagramURL: 50shadesofxen              # ignore the http://instagram.com/ part
    linkedInURL:  alexander-lee-b1a16710a" # ignore the https://ca.linkedin.com/in/ part
  annisa:
    display_name: Annisa
    first_name: Annisa
    last_name: Rizal
    twitter_username: forizzle_95
    github_username:  annisarivera
    facebookURL:  RIZZLEEEEEEEE         # ignore the https://www.facebook.com/ part
    instagramURL: annisarivera          # ignore the http://instagram.com/ part
    linkedInURL:  ben-doherty-b2a19359" # ignore the https://ca.linkedin.com/in/ part
  tiara:
    display_name: Tiara
    first_name: Tiara
    last_name: Dobbs
    twitter_username: tbag
    github_username:  notionparallax
    facebookURL:  tiara.dobbs          # ignore the https://www.facebook.com/ part
    instagramURL: Pigsu_                # ignore the http://instagram.com/ part
    linkedInURL:  ben-doherty-b2a19359" # ignore the https://ca.linkedin.com/in/ part
