title: Automatic Indoor Tracking in Workplaces
email: ben@notionparallax.co.uk
description: > # this means to ignore newlines until "baseurl:"
    This is where I write things down. It's the way I make space in my
    head for new ideas. The ideas here were what I thought at the time,
    but there is a very good chance that I no longer think that!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://where-in.space" # the base hostname & protocol for your site
twitter_username: whereinspace #the twitter account for this project

#Timezone settings
timezone: Australia/Sydney

#google analytics
GAcode: UA-52654925-12

# Build settings
permalink: "/:year/:title"
markdown: kramdown
kramdown:
  parse_block_html: true

authors:
  alex:
    display_name: Alexander Lee
    first_name: Ben
    last_name: Doherty
    twitter_username: alexlee #personal twitter account
    github_username:  notionparallax
    facebookURL:  XenriaLee          # ignore the https://www.facebook.com/ part
    instagramURL: Pigsu_                # ignore the http://instagram.com/ part
    linkedInURL:  ben-doherty-b2a19359" # ignore the https://ca.linkedin.com/in/ part
  annisa:
    display_name: Annisa
    first_name: Ben
    last_name: Doherty
    twitter_username: rollingrizlaz
    github_username:  notionparallax
    facebookURL:  RIZZLEEEEEEEE          # ignore the https://www.facebook.com/ part
    instagramURL: Pigsu_                # ignore the http://instagram.com/ part
    linkedInURL:  ben-doherty-b2a19359" # ignore the https://ca.linkedin.com/in/ part
  tiara:
    display_name: Tiara
    first_name: Ben
    last_name: Doherty
    twitter_username: tbag
    github_username:  notionparallax
    facebookURL:  tiara.dobbs          # ignore the https://www.facebook.com/ part
    instagramURL: Pigsu_                # ignore the http://instagram.com/ part
    linkedInURL:  ben-doherty-b2a19359" # ignore the https://ca.linkedin.com/in/ part
